

# ============================================================
# U-SAMNet: Uncertainty-aware Self-Attention Multi-task Network
# for Pore Detection in Additive Manufacturing
#
# Manuscript ID: applsci-4356152
# Journal: Applied Sciences (MDPI)
#
# Authors: Prosenjit Roy, Kijoon Lee, Mohsen Taheri Andani,
#          Toan Truong, Haojun You, Noushin Ghaffari
#
# Affiliation: Prairie View A&M University /
#              Texas A&M University
#
# Description: Full implementation of U-SAMNet including
# model definition, training, evaluation, and MC-dropout
# uncertainty estimation.
#
# Requirements:
#   - Python 3.9
#   - TensorFlow 2.10
#   - scikit-learn
#   - numpy
#   - CUDA 11.2, cuDNN 8.1
#
# Hardware: Bridges-2 Supercomputing System
#           Pittsburgh Supercomputing Center
#           NVIDIA Tesla V100 32GB GPU
#
# Usage:
#   1. Set dataset path in combined_dataset variable
#   2. Run: python USAMNet_training_code.py
# ============================================================

import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import (
    Input, Conv2D, MaxPooling2D, UpSampling2D,
    Concatenate, BatchNormalization, Activation,
    GlobalAveragePooling2D, GlobalMaxPooling2D,
    Dense, Dropout, Multiply, Reshape, Add)
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.image import (
    load_img, img_to_array)
from tensorflow.keras.callbacks import ReduceLROnPlateau
from sklearn.metrics import (
    accuracy_score, precision_score,
    recall_score, f1_score, confusion_matrix)
from sklearn.utils import resample

# NOTE: Before running this script, the synthetic pairs
# generated by pix2pix_synthesis.py must be copied into
# the train folder manually.
# Final train folder should contain 7,147 image-mask pairs:
#   1,147 real images + 6,000 synthetic images
combined_dataset = '/content/drive/MyDrive/ML/Unetcomb'

# ============================================================
# 1. UNCERTAINTY GUIDANCE ATTENTION (UGA) BLOCK
# ============================================================
def uag_block(x, uncertainty_map, ratio=8):
    """
    Uncertainty Guidance Attention Block.
    Suppresses channel attention weights using inverted
    epistemic uncertainty estimates.

    Args:
        x: Input feature tensor [B, H, W, C]
        uncertainty_map: Spatial uncertainty map [B, H, W, 1]
        ratio: Channel reduction ratio for SE-style attention

    Returns:
        Modulated feature tensor [B, H, W, C]
    """
    channel = x.shape[-1]
    shared_dense_one = Dense(channel // ratio, activation='relu')
    shared_dense_two = Dense(channel)

    # Channel Attention via GAP and GMP
    avg_pool = GlobalAveragePooling2D()(x)
    max_pool = GlobalMaxPooling2D()(x)
    avg_out = shared_dense_two(shared_dense_one(avg_pool))
    max_out = shared_dense_two(shared_dense_one(max_pool))

    # A_c in R^{1x1xC}
    channel_attention = Add()([avg_out, max_out])
    channel_attention = Activation('sigmoid')(channel_attention)
    channel_attention = Reshape((1, 1, channel))(channel_attention)

    # A_UGA = A_c * (1 - U_map) via broadcasting
    # (1-U_map) in R^{HxWx1} broadcasts across C channels
    # A_c in R^{1x1xC} broadcasts across HxW spatial locations
    attention_weight = Multiply()([channel_attention,
                                   1 - uncertainty_map])
    return Multiply()([x, attention_weight])

# ============================================================
# 2. U-SAMNET MODEL DEFINITION
# ============================================================
def usamnet_model(input_size=(256, 256, 1)):
    """
    U-SAMNet: Uncertainty-aware Self-Attention Multi-task Network.

    Architecture:
        - Shared U-Net encoder-decoder backbone
        - UGA block at bottleneck for uncertainty-guided attention
        - Three supervised output heads: segmentation,
          classification, denoising
        - Separate inference model for MC-dropout uncertainty

    Args:
        input_size: Input image dimensions (H, W, C)

    Returns:
        model: Training model with 3 supervised outputs
        inference_model: Inference model with 4 outputs
                        including uncertainty
    """
    inputs = Input(input_size)

    # ---- Encoder ----
    # Level 1: [B, 128, 128, 64]
    x = Conv2D(64, 3, activation='relu', padding='same')(inputs)
    x = BatchNormalization()(x)
    x = Conv2D(64, 3, activation='relu', padding='same')(x)
    skip1 = BatchNormalization()(x)

    # Level 2: [B, 64, 64, 128]
    x = MaxPooling2D()(skip1)
    x = Conv2D(128, 3, activation='relu', padding='same')(x)
    x = BatchNormalization()(x)
    x = Conv2D(128, 3, activation='relu', padding='same')(x)
    skip2 = BatchNormalization()(x)

    # Bottleneck: [B, 32, 32, 256]
    x = MaxPooling2D()(skip2)
    x = Conv2D(256, 3, activation='relu', padding='same')(x)
    x = BatchNormalization()(x)

    # ---- UGA Block ----
    # U_map in R^{32x32x1} from MC-dropout on bottleneck
    bottleneck_unc = Dropout(0.5)(x, training=True)
    uncertainty_map = Conv2D(1, 1,
                             activation='sigmoid')(bottleneck_unc)
    x = uag_block(x, uncertainty_map)

    # ---- Decoder ----
    x = UpSampling2D()(x)
    x = Concatenate()([x, skip2])
    x = Conv2D(128, 3, activation='relu', padding='same')(x)
    x = BatchNormalization()(x)

    x = UpSampling2D()(x)
    x = Concatenate()([x, skip1])
    x = Conv2D(64, 3, activation='relu', padding='same')(x)
    decoder_features = BatchNormalization()(x)

    # ---- Supervised Output Heads ----
    # Segmentation head: pixel-wise pore mask
    seg_output = Conv2D(1, 1, activation='sigmoid',
                        name='segmentation')(decoder_features)

    # Classification head: image-level pore presence
    cls_branch = GlobalAveragePooling2D()(decoder_features)
    cls_branch = Dense(64, activation='relu')(cls_branch)
    cls_branch = Dropout(0.5)(cls_branch)
    cls_output = Dense(1, activation='sigmoid',
                       name='presence')(cls_branch)

    # Denoising head: image reconstruction for regularization
    denoise_output = Conv2D(1, 1, activation='sigmoid',
                            name='denoised')(decoder_features)

    # Training model: 3 supervised outputs only
    # Uncertainty is NOT a supervised target
    model = Model(inputs,
                  outputs=[seg_output, cls_output,
                           denoise_output])

    # Inference model: includes MC-dropout uncertainty output
    # Uncertainty estimated from predictive variance (T=10 passes)
    dropout_unc = Dropout(0.5)(decoder_features, training=True)
    unc_output = Conv2D(1, 1, activation='sigmoid',
                        name='uncertainty')(dropout_unc)
    inference_model = Model(inputs,
                            outputs=[seg_output, unc_output,
                                     cls_output, denoise_output])

    return model, inference_model

# ============================================================
# 3. DATA LOADING
# ============================================================
def load_data(folder, size=(256, 256)):
    """
    Load images and masks from folder structure:
        folder/
            images/
            masks/

    Args:
        folder: Path to dataset folder
        size: Target image size (H, W)

    Returns:
        images: Normalized image array [N, H, W, 1]
        masks: Normalized mask array [N, H, W, 1]
    """
    images, masks = [], []
    img_path = os.path.join(folder, 'images')
    mask_path = os.path.join(folder, 'masks')

    for file in sorted(os.listdir(img_path)):
        img = img_to_array(load_img(
            os.path.join(img_path, file),
            color_mode="grayscale",
            target_size=size)) / 255.0
        mask = img_to_array(load_img(
            os.path.join(mask_path, file),
            color_mode="grayscale",
            target_size=size)) / 255.0
        images.append(img)
        masks.append(mask)

    return np.array(images), np.array(masks)

# ============================================================
# 4. DATASET PATHS
# ============================================================
combined_dataset = '/content/drive/MyDrive/ML/Unetcomb'
train_folder = os.path.join(combined_dataset, 'train')
test_folder  = os.path.join(combined_dataset, 'test')

X_train, Y_train = load_data(train_folder)
X_test, Y_test   = load_data(test_folder)

print(f"Training samples: {len(X_train)}")
print(f"Test samples:     {len(X_test)}")

# Binary image-level classification labels
# Derived from segmentation mask: pore present if any pixel > 0
Y_train_cls = (Y_train.sum(axis=(1,2,3)) > 0).astype(np.float32)
Y_test_cls  = (Y_test.sum(axis=(1,2,3)) > 0).astype(np.float32)

# ============================================================
# 5. BUILD AND COMPILE MODEL
# ============================================================
model, inference_model = usamnet_model()

# Three supervised tasks only.
# Uncertainty is derived from MC-dropout variance at inference.
# It is NOT trained with any loss term.
model.compile(
    optimizer='adam',
    loss={
        "segmentation": "binary_crossentropy",
        "presence":     "binary_crossentropy",
        "denoised":     "mean_squared_error"
    },
    loss_weights={
        "segmentation": 1.0,
        "presence":     1.0,
        "denoised":     1.0
    },
    metrics={
        "segmentation": ["accuracy"],
        "presence":     ["accuracy"]
    }
)

# ============================================================
# 6. TRAINING
# ============================================================
reduce_lr = ReduceLROnPlateau(
    monitor='val_segmentation_loss',
    factor=0.5,
    patience=5,
    min_lr=1e-6,
    mode='min')

history = model.fit(
    X_train,
    {
        "segmentation": Y_train,
        "presence":     Y_train_cls,
        "denoised":     X_train  # clean image as denoising target
    },
    validation_data=(
        X_test,
        {
            "segmentation": Y_test,
            "presence":     Y_test_cls,
            "denoised":     X_test
        }
    ),
    epochs=50,
    batch_size=16,
    callbacks=[reduce_lr]
)

model.save("/content/usamnet.h5")
inference_model.save("/content/usamnet_inference.h5")
print("Training complete. Models saved.")

# ============================================================
# 7. MC-DROPOUT UNCERTAINTY ESTIMATION
# ============================================================
def mc_dropout_uncertainty(inference_model, X, T=10):
    """
    Estimate epistemic uncertainty via MC-dropout.

    Performs T stochastic forward passes with dropout active
    and computes predictive variance as uncertainty estimate.

    U = (1/T) * sum((S_t - S_mean)^2)

    Args:
        inference_model: Model with dropout active at inference
        X: Input images [N, H, W, 1]
        T: Number of stochastic forward passes

    Returns:
        mean_pred: Mean segmentation prediction [N, H, W, 1]
        uncertainty: Predictive variance [N, H, W, 1]
    """
    preds = np.stack(
        [inference_model.predict(X, verbose=0)[0]
         for _ in range(T)],
        axis=0)
    uncertainty = np.var(preds, axis=0)
    mean_pred   = np.mean(preds, axis=0)
    return mean_pred, uncertainty

# ============================================================
# 8. EVALUATION
# ============================================================
# Predict using training model
outputs         = model.predict(X_test)
Y_pred_seg      = outputs[0]
Y_pred_cls      = outputs[1]
Y_pred_denoised = outputs[2]

# Uncertainty via MC-dropout using inference model
_, Y_pred_uncertainty = mc_dropout_uncertainty(
    inference_model, X_test, T=10)

# Segmentation metrics (pixel-wise)
threshold     = 0.4
Y_pred_binary = (Y_pred_seg > threshold).astype(np.uint8)
Y_test_binary = (Y_test > threshold).astype(np.uint8)
Y_test_flat   = Y_test_binary.flatten()
Y_pred_flat   = Y_pred_binary.flatten()

cm = confusion_matrix(Y_test_flat, Y_pred_flat)
tn, fp, fn, tp = cm.ravel()
iou = tp / (tp + fp + fn)

seg_accuracy  = accuracy_score(Y_test_flat, Y_pred_flat)
seg_precision = precision_score(Y_test_flat, Y_pred_flat,
                                zero_division=0)
seg_recall    = recall_score(Y_test_flat, Y_pred_flat,
                             zero_division=0)
seg_f1        = f1_score(Y_test_flat, Y_pred_flat,
                         zero_division=0)

# Classification metrics (image-wise)
Y_pred_cls_binary = (Y_pred_cls > 0.5).astype(np.uint8)
cls_accuracy  = accuracy_score(Y_test_cls, Y_pred_cls_binary)
cls_precision = precision_score(Y_test_cls, Y_pred_cls_binary,
                                zero_division=0)
cls_recall    = recall_score(Y_test_cls, Y_pred_cls_binary,
                             zero_division=0)
cls_f1        = f1_score(Y_test_cls, Y_pred_cls_binary,
                         zero_division=0)

print("\nSegmentation Metrics (pixel-wise):")
print(f"Accuracy:  {seg_accuracy*100:.2f}%")
print(f"Precision: {seg_precision*100:.2f}%")
print(f"Recall:    {seg_recall*100:.2f}%")
print(f"F1 Score:  {seg_f1*100:.2f}%")
print(f"IoU:       {iou*100:.2f}%")

print("\nClassification Metrics (image-wise):")
print(f"Accuracy:  {cls_accuracy*100:.2f}%")
print(f"Precision: {cls_precision*100:.2f}%")
print(f"Recall:    {cls_recall*100:.2f}%")
print(f"F1 Score:  {cls_f1*100:.2f}%")

# ============================================================
# 9. BOOTSTRAP CONFIDENCE INTERVALS
# ============================================================
def bootstrap_ci(y_true, y_pred, n_bootstrap=1000, ci=95):
    """
    Compute bootstrap confidence intervals for metrics.

    Args:
        y_true: Ground truth labels
        y_pred: Predicted labels
        n_bootstrap: Number of bootstrap resamples
        ci: Confidence interval percentage

    Returns:
        Dictionary with mean, std, lower, upper for each metric
    """
    metrics = {'accuracy':  [],
               'precision': [],
               'recall':    [],
               'f1':        [],
               'iou':       []}

    for _ in range(n_bootstrap):
        indices = resample(np.arange(len(y_true)),
                           replace=True)
        y_t = y_true[indices]
        y_p = y_pred[indices]

        if len(np.unique(y_t)) < 2:
            continue

        cm = confusion_matrix(y_t, y_p)
        tn, fp, fn, tp = cm.ravel()

        metrics['accuracy'].append(accuracy_score(y_t, y_p))
        metrics['precision'].append(
            precision_score(y_t, y_p, zero_division=0))
        metrics['recall'].append(
            recall_score(y_t, y_p, zero_division=0))
        metrics['f1'].append(
            f1_score(y_t, y_p, zero_division=0))
        metrics['iou'].append(
            tp / (tp + fp + fn)
            if (tp + fp + fn) > 0 else 0)

    alpha = (100 - ci) / 2
    results = {}
    for metric, values in metrics.items():
        values = np.array(values)
        results[metric] = {
            'mean':  np.mean(values),
            'std':   np.std(values),
            'lower': np.percentile(values, alpha),
            'upper': np.percentile(values, 100 - alpha)
        }
    return results

print("\nRunning bootstrap CI (n=1000)...")
ci_results = bootstrap_ci(Y_test_flat, Y_pred_flat,
                           n_bootstrap=1000, ci=95)

print("\nBootstrap CI Results (95%, n=1000):")
print(f"{'Metric':<12} {'Mean':>8} {'Std':>7} "
      f"{'Lower':>8} {'Upper':>8}")
print("-"*50)
for metric, vals in ci_results.items():
    print(f"{metric:<12} "
          f"{vals['mean']*100:>7.2f}%  "
          f"{vals['std']*100:>6.2f}%  "
          f"{vals['lower']*100:>7.2f}%  "
          f"{vals['upper']*100:>7.2f}%")

# ============================================================
# 10. UNCERTAINTY CALIBRATION METRICS
# ============================================================
from sklearn.metrics import roc_auc_score

mean_pred, uncertainty = mc_dropout_uncertainty(
    inference_model, X_test, T=10)

mean_flat = mean_pred.flatten()
unc_flat  = uncertainty.flatten()

# Brier Score
brier = np.mean((mean_flat - Y_test_flat)**2)
print(f"\nBrier Score: {brier:.4f}")

# AUROC: uncertainty as predictor of errors
errors = (Y_pred_flat != Y_test_flat).astype(int)
auroc  = roc_auc_score(errors, unc_flat)
print(f"AUROC (uncertainty vs error): {auroc:.4f}")

# ECE: Expected Calibration Error
def compute_ece(probs, labels, n_bins=10):
    bins = np.linspace(0, 1, n_bins + 1)
    ece  = 0.0
    for i in range(n_bins):
        mask = (probs >= bins[i]) & (probs < bins[i+1])
        if mask.sum() == 0:
            continue
        bin_acc  = labels[mask].mean()
        bin_conf = probs[mask].mean()
        ece += mask.mean() * abs(bin_acc - bin_conf)
    return ece

ece = compute_ece(mean_flat, Y_test_flat)
print(f"ECE: {ece:.4f}")